### ISSUE TITLE
I can see other people's mucked losing hands

### ISSUE THREAD

**Issue by DamienBlack** [hippich/Bitcoin-Poker-Room#22]
Firefox 4
Windows 7

The dealer accurately reports when someone mucks a losing hand, but I can still see it. A mucked losing hand is not supposed to be shown to anyone.

This seems very high priority to me.

**Comment by anisoptera** [comment]
All hands that make it to showdown are shown, regardless of the muck setting. This is temporary until we implement a way for players to retrieve hand histories, which will show all hands that made it to showdown, as long as the player was involved in the hand.

Because this is a temporary fix, the dealer log still reports that hands are mucked, even though they aren't.

**Comment by DamienBlack** [comment]
But even when looking through hand histories, you shouldn't be able to see the cards that were mucked, right?

**Comment by anisoptera** [comment]
Hands mucked at showdown are available upon request in brick and mortar poker rooms. Online, requesting a hand history is considered to be the same thing. In all online poker rooms, cards mucked at showdown are visible in the hand history (to players that participated in the hand).

**Comment by DamienBlack** [comment]
Oh ok, didn't know that.
