### ISSUE TITLE
Feature Request: Ratholing?

### ISSUE THREAD

**Issue by DamienBlack** [hippich/Bitcoin-Poker-Room#23]
A player I was playing with pointed out that "ratholing" is not allowed in most poker rooms. according to http://www.pokertips.org/glossary/w/RATHOLING:

Ratholing means to leave a game and then come back into the game with a smaller stack then with which you left. For example, suppose you buy into a game for $20. You go on a winning streak and increase your stack to $100. Now, you feel uncomfortable playing with this much money, so you leave the game, pocket $80, and re-enter the game with only $20. This would be a case of ratholing. Ratholing is poor poker etiquette, and most poker rooms prohibit it.

Since it seems that most rooms don't allow this, perhaps it should be implemented here. (although I do not see the problem)

**Comment by hippich** [comment]
Thank you for suggestion. I'd probably put this on poll, since for me - I'd like to be able to remove part of money I won from the stack and never thought it's bad etiquette. But will see if people thing this should be implemented.

**Comment by anisoptera** [comment]
I feel like this should be implemented at some point. The reason it's bad etiquette is that you are taking my money off the table, but still playing against me - if you want to quit, fine, but if you are going to keep playing, let me have the chance to win my money back. In heads-up, both players sometimes agree to move to a new table because they have gotten too deep; the idea is that all players should have to agree on changing the stakes, even when the "stakes" in question are just how much money is on the table.

That said, I don't know how difficult this will be to implement, but it isn't high priority because I don't remember ever getting any complaints about it before. So we can just put it to a vote to see how important it is to our player base right now.

**Comment by anisoptera** [comment]
Implemented in 8468277.
