### ISSUE TITLE
There needs to be a 5 minute timeout so people can't just sit down and take up a seat all day without playing.

### ISSUE THREAD

**Issue by hippich** [hippich/Bitcoin-Poker-Room#64]

**Comment by anisoptera** [comment]
Currently we punt users when they miss a certain number of hands. Is this a problem with heads-up tables?

**Comment by hippich** [comment]
So user can't just sit out forever, right? eventually it will be removed from seat if he did not play certain number of hands?

**Comment by anisoptera** [comment]
Yes, the only way someone can take up a seat "forever" is if no hands are ever played at the table. After they miss a certain number of hands in a row they will be removed (I think the default is 5 - it's configurable)

I can see this being a problem at heads-up tables, because if I'm sitting out at a table with 2 seats, no hands can be played at that table and I'll never be kicked out. But in that case I think the solution is spawning new HU tables when there aren't any empty ones.

**Comment by hippich** [comment]
Thank you for clarification. Closing.

**Comment by hippich** [comment]
Apparently, it do not work.. Today I seen three users sitting a very long time. Two one even without any stack on table.. Probably something somewhere broken.

**Comment by anisoptera** [comment]
That'll teach me to assume something works just because I read the implementation and it made sense.
